"""Add provider state

Revision ID: 17f4b0fbca2b
Revises: 2d8c48d24486
Create Date: 2026-09-08 17:56:46.139277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f4b0fbca2b'
down_revision: Union[str, Sequence[str], None] = '2d8c48d24486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_state',
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('lifetime_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('provider_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_state')
    # ### end Alembic commands ###
