"""add search cycle usage and execution tracking

Revision ID: 1b4a30ce5862
Revises: a57e00570001
Create Date: 2026-09-10 09:07:52.579508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4a30ce5862'
down_revision: Union[str, Sequence[str], None] = 'a57e00570001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_cycle_usage',
    sa.Column('cycle_id', sa.String(length=64), nullable=False),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cycle_id')
    )
    op.add_column('search_execution', sa.Column('cycle_id', sa.String(length=64), nullable=True))
    op.create_index('idx_search_execution_cycle', 'search_execution', ['cycle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_search_execution_cycle', table_name='search_execution')
    op.drop_column('search_execution', 'cycle_id')
    op.drop_table('search_cycle_usage')
    # ### end Alembic commands ###
