"""search quality telemetry

Revision ID: 2f8e25ff3da4
Revises: 1acfb3f85bd0
Create Date: 2026-09-16 19:43:03.348435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8e25ff3da4'
down_revision: Union[str, Sequence[str], None] = '1acfb3f85bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_execution', sa.Column('query_variant', sa.String(length=100), nullable=True))
    op.add_column('search_execution', sa.Column('jobs_fresher_eligible', sa.Integer(), nullable=True))
    op.add_column('search_execution', sa.Column('recommendations_created', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_execution', 'recommendations_created')
    op.drop_column('search_execution', 'jobs_fresher_eligible')
    op.drop_column('search_execution', 'query_variant')
    # ### end Alembic commands ###
