"""add_provider_minute_usage

Revision ID: 785c04c7fe14
Revises: 3b0000000000
Create Date: 2026-09-09 11:00:42.915615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785c04c7fe14'
down_revision: Union[str, Sequence[str], None] = '3b0000000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_minute_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('usage_minute', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', 'usage_minute', name='uq_provider_minute')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_minute_usage')
    # ### end Alembic commands ###
