"""add_source_execution_id

Revision ID: 8da5c3cbdffc
Revises: 4b568321e102
Create Date: 2026-09-23 12:48:17.177164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da5c3cbdffc'
down_revision: Union[str, Sequence[str], None] = '4b568321e102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_enrichments', sa.Column('source_execution_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_job_enrichments_source_execution_id', 'job_enrichments', 'search_execution', ['source_execution_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_job_enrichments_source_execution_id', 'job_enrichments', type_='foreignkey')
    op.drop_column('job_enrichments', 'source_execution_id')
    # ### end Alembic commands ###
