"""a6 deduplication and recommendation

Revision ID: b64748522884
Revises: 7047f08b3e8e
Create Date: 2026-09-14 19:12:30.016138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64748522884'
down_revision: Union[str, Sequence[str], None] = '7047f08b3e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_job_sources_source_source_job_id')
    )
    op.create_index(op.f('ix_job_sources_job_id'), 'job_sources', ['job_id'], unique=False)
    op.create_table('recommendation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('recommended_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_recommendation_history_user_job')
    )
    op.create_index(op.f('ix_recommendation_history_job_id'), 'recommendation_history', ['job_id'], unique=False)
    op.create_index(op.f('ix_recommendation_history_user_id'), 'recommendation_history', ['user_id'], unique=False)
    op.add_column('jobs', sa.Column('canonical_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_jobs_canonical_hash'), 'jobs', ['canonical_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_canonical_hash'), table_name='jobs')
    op.drop_column('jobs', 'canonical_hash')
    op.drop_index(op.f('ix_recommendation_history_user_id'), table_name='recommendation_history')
    op.drop_index(op.f('ix_recommendation_history_job_id'), table_name='recommendation_history')
    op.drop_table('recommendation_history')
    op.drop_index(op.f('ix_job_sources_job_id'), table_name='job_sources')
    op.drop_table('job_sources')
    # ### end Alembic commands ###
