"""add_search_execution

Revision ID: d28fd382ebb8
Revises: 785c04c7fe14
Create Date: 2026-09-09 12:27:11.145087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28fd382ebb8'
down_revision: Union[str, Sequence[str], None] = '785c04c7fe14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jobs_fetched', sa.Integer(), nullable=True),
    sa.Column('jobs_created', sa.Integer(), nullable=True),
    sa.Column('jobs_duplicates', sa.Integer(), nullable=True),
    sa.Column('jobs_invalid', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_execution_candidate', 'search_execution', ['candidate_id'], unique=False)
    op.create_index('idx_search_execution_status', 'search_execution', ['status'], unique=False)
    op.create_index('uq_active_claim', 'search_execution', ['candidate_id'], unique=True, postgresql_where=sa.text("status = 'selected'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_claim', table_name='search_execution', postgresql_where=sa.text("status = 'selected'"))
    op.drop_index('idx_search_execution_status', table_name='search_execution')
    op.drop_index('idx_search_execution_candidate', table_name='search_execution')
    op.drop_table('search_execution')
    # ### end Alembic commands ###
