"""add description_is_snippet

Revision ID: e28fe4a4daca
Revises: 202609191045
Create Date: 2026-09-21 21:32:11.321772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28fe4a4daca'
down_revision: Union[str, Sequence[str], None] = '202609191045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('description_is_snippet', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'description_is_snippet')
    # ### end Alembic commands ###
